### ISSUE TITLE
Can i check if a required plugin was installed and is active?

### ISSUE THREAD

**Issue by Karzin** [thomasgriffin/TGM-Plugin-Activation#201]
I know there is a native wordpress function that checks it for me (http://codex.wordpress.org/Function_Reference/is_plugin_active)

But i want to know if this library can check it also, because it would be easier.

**Comment by GaryJones** [comment]
Can you please explain more what you're after here?

**Comment by pablo-pacheco** [comment]
I'm using TGM inside my plugin, instead of using it inside a theme.

So when the user install my plugin, i can't consider that the required plugins handled by TGM are already downloaded and active. I need to check if they really are before i start using them. 

I just wanted to know if there is some sort of public method i could use to test that. I think there could be one because TGM needs to know it too right?

**Comment by GaryJones** [comment]
What's wrong with `is_plugin_active()`? That's what TGMPA uses quite often (and `is_plugin_inactive()`).

**Comment by jrfnl** [comment]
Side note: `is_plugin_active()` will work for 'normal' plugins, not for must-use/dropins, so is not fool-proof.
See: https://core.trac.wordpress.org/ticket/24205

**Comment by GaryJones** [comment]
Fair point, but either way, I don't think is something TGMPA should be handling specifically - it should be in core.

**Comment by jrfnl** [comment]
@GaryJones I absolutely agree, which is why I reported it as a bug in core :sunglasses: Just thought it would be good to raise some awareness of the bug.
