### ISSUE TITLE
Warning: More than one text-domain is being used in this theme. 

### ISSUE THREAD

**Issue by nandlal-tjm** [thomasgriffin/TGM-Plugin-Activation#618]
I am using new version 2.6.1 of TGM download via Custom TGMPA Generator for my theme.  I intend to distribute the theme on themeforest.
I got following error:

> Warning: More than one text-domain is being used in this theme. This means the theme will not be compatible with WordPress.org language packs.
> The domains found are vtheme, tgmpa

Why not replace text domain in class file for themeforest theme?
Is this error acceptable by themeforest reviewer? 
Any other suggestion to prevent from this error.

**Comment by jrfnl** [comment]
> Why not replace text domain in class file for themeforest theme?

Because TF does not use the WP.org language packs and it will save your theme translators a bunch of work as TGMPA already ships with translations in 17 languages.

> Is this error acceptable by themeforest reviewer? 

Yes it is.

> Any other suggestion to prevent from this error.

You can choose 'distribution via WP.org' in the Custom Generator anyway, but it really isn't the right choice.

For more detail about the difference between the versions, see https://github.com/TGMPA/TGM-Plugin-Activation/pull/519
