### ISSUE TITLE
Is there a way to call two different instances?

### ISSUE THREAD

**Issue by manandharsudin** [thomasgriffin/TGM-Plugin-Activation#650]
Hi there,

I wanted to required a plugin which is not dismissable and a recommend a plugin which is dismissable. Is there a way to call two different instances of TGMPA or any other way to do that?
Currently when I recommend and required in separate callback it doesn't works.

Thanks in advance

**Comment by jrfnl** [comment]
TGMPA is set up to gather all the required/recommended plugins information on one page, both from themes as well as plugins with dependencies. This is by design as it would be pretty bad from an end-user usability perspective if there would be two or more such pages.
So no, you can not have two instances of TGMPA.
