### ISSUE TITLE
Parent menu slug does not work in $config

### ISSUE THREAD

**Issue by rinkuyadav999** [thomasgriffin/TGM-Plugin-Activation#672]
Hi

I have downloaded class-tgm-plugin-activation for theme and it adds link under themes.php perfectly using config:

`$config = array(
		'id'           => 'mytheme',
		'default_path' => '', 
		'menu'         => 'mytheme-install-plugins',
		'has_notices'  => true,
		'dismissable'  => true,
		'dismiss_msg'  => '',
		'is_automatic' => false,
		'message'      => '',
	);`

But i want to display link under plugins.php instead themes.php so i added
'parent_slug'  => 'plugins.php',
'capability'   => 'manage_options'
But it keeps link under themes.php. Expecting sub menu of plugins.php

**Comment by jrfnl** [comment]
Hi @rinkuyadav999, to help you I need a little more information. Could you answer the following questions ?

* Did you download the zip from this repo or did you use the Custom TGMPA Generator on the website ?
* If the Custom TGMPA Generator: which choices did you make in the form ?
* From your message I gather you are including TGMPA in a theme, nor a plugin. Is that correct ?

**Comment by rinkuyadav999** [comment]
Hi @jrfnl 

- I used Custom TGMPA Generator on the website.
- I chosen theme because i want to use it in theme.
- Yes i am using in theme.

Everything works fine, just i want to display link of 'install plugin' under plugins.php instead themes.php

**Comment by jrfnl** [comment]
Hi @rinkuyadav999, 

Did you choose "WordPress.org" or "ThemeForest" as the publication channel for the theme when you downloaded ? If so, that's the reason.

The [theme review rules](https://developer.wordpress.org/themes/getting-started/) for themes which are to be published in the WP theme repository (same goes for ThemeForest) do not allow for themes to add an admin page anywhere but under the "Themes" menu, so that functionality gets disabled for the WP version generated by the Custom TGMPA Generator.
If you don't intend to publish the theme in the WP theme repository or via ThemeForest, just choose "other publication channel" in the form and you'll receive a full featured version of TGMPA ;-)

For more information about the different versions generated by the Custom TGMPA Generator, see #519.

Does that solve your issue ?

**Comment by rinkuyadav999** [comment]
Yes it is TRT cap :(
